apiVersion: apps/v1
kind: Deployment
metadata:
  name:  login-service-app
  labels:
    app:  login-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  login-service-app
  template:
    metadata:
      labels:
        app:  login-service-app
    spec:
      containers:
      - name:  login-service-app
        image: hiransanjeewa/springboot-backend-config-server:login-service
        ports:
        - containerPort: 9001

---

apiVersion: v1
kind: Service
metadata:
  name: login-service-svc
spec:
  selector:
    app.kubernetes.io/name: login-service-app
  ports:
    - port: 80
      targetPort: 9001