apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-service-app
  labels:
    app: register-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register-service-app
  template:
    metadata:
      labels:
        app: register-service-app
    spec:
      containers:
        - name: register-service-app
          image: hiransanjeewa/springboot-backend-config-server:register-service
          imagePullPolicy: Always
          ports:
            - containerPort: 9002

---
apiVersion: v1
kind: Service
metadata:
  name: register-service-app-svc
spec:
  ports:
    - targetPort: 9002
      port: 80
  selector:
    app: register-service-app